version: '3.8'

networks:
  servers:

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    command: db
    networks:
      - servers
    ports:
      - "8082:8082"
    volumes:
      - ./data:/opt/practice-4/data

  balancer:
    build: .
    entrypoint: ["/opt/practice-4/lb", "--trace=true"]
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    command: server
    environment:
      - TEAM_NAME=server1
      - DB_DIR=/opt/practice-4/data
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    command: server
    environment:
      - TEAM_NAME=server2
      - DB_DIR=/opt/practice-4/data
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    command: server
    environment:
      - TEAM_NAME=server3
      - DB_DIR=/opt/practice-4/data
    depends_on:
      - db
    networks:
      - servers
    ports:
      - "8083:8080"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer
    environment:
      - INTEGRATION_TEST=1
