services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer
    environment:
      - INTEGRATION_TEST=1

  balancer:
    build: .
    entrypoint: ["/opt/practice-4/lb", "--trace=true"]
    networks:
      - servers

  server1:
    build: .
    command: server
    environment:
      - TEAM_NAME=server1
    networks:
      - servers

  server2:
    build: .
    command: server
    environment:
      - TEAM_NAME=server2
    networks:
      - servers

  server3:
    build: .
    command: server
    environment:
      - TEAM_NAME=server3
    networks:
      - servers

networks:
  servers:
